services:
  - type: web
    name: sadbhaav-spices
    runtime: node
    buildCommand: npm install && npx prisma migrate deploy && npm run build
    startCommand: node dist/server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
